1. 数据获取：数据集已下载至`bike.csv`文件中，请使用pandas库读取该文件。

In [1]:
import pandas as pd

# 读取 CSV 文件
df = pd.read_csv('data/bike.csv')

# 打印 DataFrame
print(df)

         id  city  hour  is_workday  weather  temp_1  temp_2  wind    y
0         1     0    22           1        2     3.0     0.7     0   15
1         2     0    10           1        1    21.0    24.9     3   48
2         3     0     0           1        1    25.3    27.4     0   21
3         4     0     7           0        1    15.7    16.2     0   11
4         5     1    10           1        1    21.1    25.0     2   39
...     ...   ...   ...         ...      ...     ...     ...   ...  ...
9995   9996     0     4           0        2     8.3     7.3     0    2
9996   9997     1     5           0        1    22.3    22.2     0    1
9997   9998     1     0           0        1     9.6     9.7     0   11
9998   9999     0    18           0        2    27.4    29.7     1  105
9999  10000     0     9           1        2     3.2    -2.1     2   48

[10000 rows x 9 columns]


 2. 数据预处理 I：`id`属性对构建回归预测模型没有帮助，请剔除掉该列。

In [3]:
# 删除指定列
df = df.drop(columns=['id'])

# 打印删除列后的 DataFrame
print("\n删除 'id' 列后的 DataFrame:")
print(df)


删除 'id' 列后的 DataFrame:
      city  hour  is_workday  weather  temp_1  temp_2  wind    y
0        0    22           1        2     3.0     0.7     0   15
1        0    10           1        1    21.0    24.9     3   48
2        0     0           1        1    25.3    27.4     0   21
3        0     7           0        1    15.7    16.2     0   11
4        1    10           1        1    21.1    25.0     2   39
...    ...   ...         ...      ...     ...     ...   ...  ...
9995     0     4           0        2     8.3     7.3     0    2
9996     1     5           0        1    22.3    22.2     0    1
9997     1     0           0        1     9.6     9.7     0   11
9998     0    18           0        2    27.4    29.7     1  105
9999     0     9           1        2     3.2    -2.1     2   48

[10000 rows x 8 columns]


3. 数据预处理 II：我们暂不考虑不同城市对单车租用的影响，请筛选出上海市的所有数据，然后剔除`city`列。

> 提示：目前剩余4,998条数据。

In [12]:
sh = df[df['city']==1]
sh = sh.drop(columns=['city'])
print(sh)

      hour  is_workday  weather  temp_1  temp_2  wind    y
4       10           1        1    21.1    25.0     2   39
5        0           1        1    20.4    18.2     0   12
9        4           1        3    17.4    18.0     3    2
10       0           1        1    14.9    15.3     2    6
11       8           0        1    25.0    28.1     0   25
...    ...         ...      ...     ...     ...   ...  ...
9990    23           1        2    19.2    19.9     1   44
9991    19           1        1    25.1    26.2     2  124
9993     5           1        3    13.7    14.1     2    1
9996     5           0        1    22.3    22.2     0    1
9997     0           0        1     9.6     9.7     0   11

[4998 rows x 7 columns]


4. 数据预处理 III：为简化数据，请将`hour`列中原来6点-18点统一为1；19点-次日5点统一为0。

In [13]:
import numpy as np
sh.loc[:, 'hour'] = np.where((sh['hour'] >= 6) & (sh['hour'] <= 18), 1, 0)
print(sh)

      hour  is_workday  weather  temp_1  temp_2  wind    y
4        1           1        1    21.1    25.0     2   39
5        0           1        1    20.4    18.2     0   12
9        0           1        3    17.4    18.0     3    2
10       0           1        1    14.9    15.3     2    6
11       1           0        1    25.0    28.1     0   25
...    ...         ...      ...     ...     ...   ...  ...
9990     0           1        2    19.2    19.9     1   44
9991     0           1        1    25.1    26.2     2  124
9993     0           1        3    13.7    14.1     2    1
9996     0           0        1    22.3    22.2     0    1
9997     0           0        1     9.6     9.7     0   11

[4998 rows x 7 columns]


5. 数据预处理 IV：`y`列为单车租用数量，是我们的预测目标（标签），请将该列提取出来，并转换为一个numpy**列向量**，将原先的`y`列剔除。

In [14]:
y = sh['y'].values.reshape(-1, 1)
print("y 列的 NumPy 列向量: \n")
print(y)
sh = sh.drop(columns=['y'])
print("\n删除 'y' 列后的 数据:")
print(sh)

y 列的 NumPy 列向量: 

[[39]
 [12]
 [ 2]
 ...
 [ 1]
 [ 1]
 [11]]

删除 'y' 列后的 数据:
      hour  is_workday  weather  temp_1  temp_2  wind
4        1           1        1    21.1    25.0     2
5        0           1        1    20.4    18.2     0
9        0           1        3    17.4    18.0     3
10       0           1        1    14.9    15.3     2
11       1           0        1    25.0    28.1     0
...    ...         ...      ...     ...     ...   ...
9990     0           1        2    19.2    19.9     1
9991     0           1        1    25.1    26.2     2
9993     0           1        3    13.7    14.1     2
9996     0           0        1    22.3    22.2     0
9997     0           0        1     9.6     9.7     0

[4998 rows x 6 columns]


6. 数据预处理 V：请将DataFrame对象转换为Numpy数组，方便后续操作。

In [15]:
array = sh.to_numpy()
print("\n 使用 .to_numpy() 方法")
print(array)


 使用 .to_numpy() 方法
[[ 1.   1.   1.  21.1 25.   2. ]
 [ 0.   1.   1.  20.4 18.2  0. ]
 [ 0.   1.   3.  17.4 18.   3. ]
 ...
 [ 0.   1.   3.  13.7 14.1  2. ]
 [ 0.   0.   1.  22.3 22.2  0. ]
 [ 0.   0.   1.   9.6  9.7  0. ]]


7. 数据集划分：请按照训练集与测试集8:2的比例将原始数据集划分。

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(array, y, test_size=0.2, random_state=42)

8. 数据预处理 VI：请分别对训练集数据、训练集标签、测试集数据和测试集标签进行归一化。

In [17]:
from sklearn.preprocessing import MinMaxScaler

# 打印划分后的数据集
print("原始训练集特征 X_train:")
print(X_train)
print("原始训练集标签 y_train:")
print(y_train)
print("原始测试集特征 X_test:")
print(X_test)
print("原始测试集标签 y_test:")
print(y_test)

# 归一化特征数据
scaler = MinMaxScaler()

# 拟合训练集特征数据并进行归一化
X_train_scaled = scaler.fit_transform(X_train)

# 使用训练集的参数对测试集进行归一化
X_test_scaled = scaler.transform(X_test)

# 归一化标签数据（可选）
y_scaler = MinMaxScaler()

# 拟合训练集标签数据并进行归一化
y_train_scaled = y_scaler.fit_transform(y_train.reshape(-1, 1)).flatten()

# 使用训练集的参数对测试集标签进行归一化
y_test_scaled = y_scaler.transform(y_test.reshape(-1, 1)).flatten()

# 打印归一化后的数据集
print("\n归一化后的训练集特征 X_train_scaled:")
print(X_train_scaled)
print("\n归一化后的训练集标签 y_train_scaled:")
print(y_train_scaled)
print("\n归一化后的测试集特征 X_test_scaled:")
print(X_test_scaled)
print("\n归一化后的测试集标签 y_test_scaled:")
print(y_test_scaled)

原始训练集特征 X_train:
[[ 1.   1.   1.  22.2 25.1  3. ]
 [ 1.   1.   1.   1.3 -2.1  1. ]
 [ 1.   1.   1.  26.6 28.8  1. ]
 ...
 [ 1.   0.   1.  25.7 27.9  1. ]
 [ 1.   1.   1.  19.7 20.5  0. ]
 [ 1.   0.   1.   1.8 -2.5  2. ]]
原始训练集标签 y_train:
[[108]
 [ 22]
 [ 60]
 ...
 [108]
 [129]
 [  9]]
原始测试集特征 X_test:
[[ 0.   0.   1.   4.6  4.4  0. ]
 [ 0.   1.   2.  -0.1 -3.6  1. ]
 [ 1.   1.   1.  27.4 28.7  4. ]
 ...
 [ 1.   1.   1.  25.3 26.5  0. ]
 [ 1.   1.   1.  29.9 33.3  2. ]
 [ 1.   0.   1.  34.7 40.4  2. ]]
原始测试集标签 y_test:
[[  1]
 [  2]
 [ 61]
 [ 36]
 [  2]
 [169]
 [ 18]
 [ 29]
 [ 12]
 [ 16]
 [120]
 [122]
 [ 95]
 [  3]
 [ 33]
 [ 31]
 [ 66]
 [ 45]
 [162]
 [ 12]
 [ 27]
 [ 32]
 [  6]
 [  2]
 [ 69]
 [124]
 [ 12]
 [159]
 [ 92]
 [ 30]
 [ 62]
 [ 69]
 [ 46]
 [ 12]
 [  6]
 [  4]
 [ 59]
 [ 27]
 [ 47]
 [146]
 [ 34]
 [  1]
 [  3]
 [ 63]
 [  1]
 [ 56]
 [  0]
 [ 34]
 [  2]
 [  5]
 [ 38]
 [  2]
 [  9]
 [  6]
 [ 27]
 [ 27]
 [  8]
 [ 18]
 [ 45]
 [  3]
 [ 45]
 [  1]
 [ 54]
 [  1]
 [ 63]
 [ 40]
 [ 42]
 [ 48]
 [

9. 模型构建：请先构建一个**线性回归模型（多元一次函数）**，然后利用训练集训练模型。

In [18]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression


# 构建线性回归模型
model = LinearRegression()

# 使用训练集训练模型
model.fit(X_train_scaled, y_train)

# 预测训练集和测试集的结果
y_train_pred = model.predict(X_train_scaled)
y_test_pred = model.predict(X_test_scaled)

# 计算模型的性能指标
train_mse = mean_squared_error(y_train, y_train_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
test_r2 = r2_score(y_test, y_test_pred)

# 打印模型的性能指标
print("训练集 MSE:", train_mse)
print("训练集 R^2:", train_r2)
print("测试集 MSE:", test_mse)
print("测试集 R^2:", test_r2)

# 打印模型的系数和截距
print("模型系数:", model.coef_)
print("模型截距:", model.intercept_)

训练集 MSE: 994.784709028871
训练集 R^2: 0.38196003909473375
测试集 MSE: 996.5688433356044
测试集 R^2: 0.3718395317360643
模型系数: [[ 33.14686071  -0.55446073 -15.38569688  26.87019273  55.03201295
    5.07876344]]
模型截距: [-12.80682748]


10. 模型测试：利用测试集对训练好的模型进行评估。

> 提示：使用`predict(data_array)`方法输入测试集，该函数返回值为模型预测值。

In [ ]:
# 计算模型的性能指标
train_mse = mean_squared_error(y_train, y_train_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
test_r2 = r2_score(y_test, y_test_pred)

# 打印模型的性能指标
print("训练集 MSE:", train_mse)
print("训练集 R^2:", train_r2)
print("测试集 MSE:", test_mse)
print("测试集 R^2:", test_r2)

# 打印模型的系数和截距
print("模型系数:", model.coef_)
print("模型截距:", model.intercept_)

11. 模型评估：请使用均方根误差（RMSE）作为评估指标，并输出RMSE值。

均方根误差(Root of Mean Squared Error)，公式为
$$
RMSE=\sqrt{\frac{1}{n}\sum_{i=1}^n(\hat{y_i}-y_i)^2}
$$
可以直接通过对MSE求平方根获得。

In [19]:
train_rmse = np.sqrt(train_mse)
print("训练集 RMSE:", train_rmse)

训练集 RMSE: 31.540207815245463
